version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "308414301876"
    AWS_REGION: "us-east-1"

phases:
  pre_build:
    commands:
      - echo "Login en Docker Hub..."
      - echo $DOCKERHUB_PASS | docker login --username $DOCKERHUB_USER --password-stdin
      
      - echo "Iniciando sesión en Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      
      - REPO_FRONT=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/devkubctl-frontend
      - REPO_BACK=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/devkubctl-backend

  build:
    commands:
      - echo "Verificando carpetas actuales..."
      - ls -la
      
      - echo "Compilando Backend (Java)..."
      # Usamos el nombre exacto de tu carpeta en GitHub
      - cd DevKubBack && chmod +x mvnw && ./mvnw clean package -DskipTests && cd ..
      
      - echo "Construyendo imágenes Docker..."
      - docker build -t $REPO_FRONT:latest ./Frontend
      - docker build -t $REPO_BACK:latest ./DevKubBack

  post_build:
    commands:
      - echo "Subiendo imágenes a ECR..."
      - docker push $REPO_FRONT:latest
      - docker push $REPO_BACK:latest
      
      - echo "Generando archivos para el despliegue en ECS..."
      - printf '[{"name":"frontend","imageUri":"%s"}]' $REPO_FRONT:latest > imagedef_frontend.json
      - printf '[{"name":"backend","imageUri":"%s"}]' $REPO_BACK:latest > imagedef_backend.json

artifacts:
  files:
    - imagedef_frontend.json
    - imagedef_backend.json
